version: "3.7"
services:
  app:
    image: kooldev/node:16
    command: ["npm", "run", "dev"]
    ports:
      - "${KOOL_APP_PORT:-${PORT_APP}}:${PORT_APP}"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  mongodb:
    image: mongo:latest
    networks:
      - kool_local
      - kool_global
    ports:
      - 1111:27017
    volumes:
      - database:/var/lib/mongo
    environment:
      ME_CONFIG_MONGODB_URL: ${URL_MONGODB}

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database: